appId: com.whatsapptoexcel.app
productName: WhatsApp To Excel
directories:
  output: dist
  buildResources: build
files:
  - main.js
  - preload.js
  - server.js
  - public/**/*
  - node_modules/**/*
  - package.json
  - extracciones/**/*
asar: true
compression: maximum

win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/icon.ico
  publisherName: WhatsApp To Excel
  verifyUpdateCodeSignature: false
  artifactName: ${productName}-${version}-${arch}.${ext}

nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: WhatsApp To Excel

mac:
  target: dmg
  icon: public/icon.icns
  category: public.app-category.productivity

linux:
  target: AppImage
  icon: public/icon.png
  category: Utility 